name: golange2e

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/#0_0_*_*_0
#defaults:
#  run:
#    working-directory: go

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - run: curl -vsS https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh | bash
        name: download fabric sample following official guide
      - run: ./network.sh up
        working-directory: fabric-samples/test-network
        name: set up network
      - run: mkdir -p ../organizations && cp -r ../../fabric-samples/test-network/organizations/* ../organizations/ && ls ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        working-directory: go/e2e
        name: prepare msp for test
      # todo remove with golang
      - run: go test -v ./...
        working-directory: go/e2e
        name: create channel
      # skip as join channel tbd
      - run: echo y |  ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go/ -ccl go
        working-directory: fabric-samples/test-network
        name: install chaincode-go
      # end of todo scope



